# Guides: https://confluence.atlassian.com/x/e8YWN for more examples.
#          - apt-add-repository ppa:sergey-dryabzhinsky/php53
#          - apt-add-repository ppa:sergey-dryabzhinsky/packages

pipelines:
  default:
    caches:
      - composer
  parallel:
    - step:
        name: NetCURL 6.1/PHP 7.1
        image: php:7.1
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip php-soap libxml2-dev git
          - docker-php-ext-install soap
          - docker-php-ext-enable soap
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - composer require phpunit/phpunit
          - vendor/bin/phpunit --configuration ./phpunit.xml
  definitions:
    services:
      docker:
        memory: 4096
